using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace DarkerWeatherNights;

public static class Program
{
    private static Lazy<DarkerWeatherNightsSettings> _settings = null!;

    public static Task<int> Main(string[] args)
    {
        return SynthesisPipeline.Instance
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .SetAutogeneratedSettings(
                nickname: "Darker Weather Nights",
                path: "DarkerWeatherNights.Settings.json",
                setting: out _settings)
            .SetTypicalOpen(GameRelease.SkyrimSE, "Darker Weather Nights.esp")
            .Run(args);
    }

    private static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var settings = _settings.Value;
        settings.Validate();

        var processor = new WeatherProcessor(state, settings);
        processor.Run();
    }
}
